create table Employees (
	id INT,
	name VARCHAR(50),
	department VARCHAR(50),
	salary DECIMAL(6,2)
);
insert into Employees (id, name, department, salary) values (1, 'Sapphire Balsom', 'Sales', 2191.81);
insert into Employees (id, name, department, salary) values (2, 'Aviva Hallybone', 'Product Management', 4331.51);
insert into Employees (id, name, department, salary) values (3, 'Johnath Barrow', 'Research and Development', 1218.22);
insert into Employees (id, name, department, salary) values (4, 'Calley Dunk', 'Services', 3549.51);
insert into Employees (id, name, department, salary) values (5, 'Rutherford Gilliat', 'Business Development', 1647.08);
insert into Employees (id, name, department, salary) values (6, 'Arie Obal', 'Training', 3633.13);
insert into Employees (id, name, department, salary) values (7, 'Stillman Eastham', 'Legal', 3710.69);
insert into Employees (id, name, department, salary) values (8, 'Timmie Dawidsohn', 'Research and Development', 1592.69);
insert into Employees (id, name, department, salary) values (9, 'Nappie Vuittet', 'Sales', 4086.26);
insert into Employees (id, name, department, salary) values (10, 'Byram Jilkes', 'Legal', 3091.17);
insert into Employees (id, name, department, salary) values (11, 'Bendite Giacobilio', 'Training', 1711.91);
insert into Employees (id, name, department, salary) values (12, 'Ayn Boughtwood', 'Engineering', 4426.51);
insert into Employees (id, name, department, salary) values (13, 'Alyss Benam', 'Engineering', 3037.14);
insert into Employees (id, name, department, salary) values (14, 'Dannie Addinall', 'Sales', 3433.06);
insert into Employees (id, name, department, salary) values (15, 'Linda Summerly', 'Human Resources', 2376.74);
insert into Employees (id, name, department, salary) values (16, 'Dianna St. Louis', 'Product Management', 1759.49);
insert into Employees (id, name, department, salary) values (17, 'Pauletta Sowrey', 'Human Resources', 1643.29);
insert into Employees (id, name, department, salary) values (18, 'Polly Hele', 'Engineering', 4616.23);
insert into Employees (id, name, department, salary) values (19, 'Tobye Chooter', 'Human Resources', 2752.15);
insert into Employees (id, name, department, salary) values (20, 'Klemens Coppenhall', 'Research and Development', 4147.73);
insert into Employees (id, name, department, salary) values (21, 'Mattias Paulou', 'Research and Development', 1664.01);
insert into Employees (id, name, department, salary) values (22, 'Eydie Beceril', 'Services', 4355.5);
insert into Employees (id, name, department, salary) values (23, 'Betteann Bonner', 'Research and Development', 4399.66);
insert into Employees (id, name, department, salary) values (24, 'Zed Amphlett', 'Research and Development', 2200.36);
insert into Employees (id, name, department, salary) values (25, 'Miof mela Mayho', 'Business Development', 2198.49);
insert into Employees (id, name, department, salary) values (26, 'Daria Pendergrast', 'Business Development', 3478.34);
insert into Employees (id, name, department, salary) values (27, 'Eartha Ber', 'Business Development', 1678.53);
insert into Employees (id, name, department, salary) values (28, 'Etty Gerrets', 'Legal', 3033.99);
insert into Employees (id, name, department, salary) values (29, 'Nikolas Bettesworth', 'Engineering', 1278.66);
insert into Employees (id, name, department, salary) values (30, 'Dixie Portch', 'Engineering', 4633.44);
insert into Employees (id, name, department, salary) values (31, 'Tucky MacAlpine', 'Support', 3623.16);
insert into Employees (id, name, department, salary) values (32, 'Lorilee Fresson', 'Research and Development', 1358.46);
insert into Employees (id, name, department, salary) values (33, 'Jessalyn Bransby', 'Business Development', 1531.6);
insert into Employees (id, name, department, salary) values (34, 'Raphael Littlejohn', 'Accounting', 4240.23);
insert into Employees (id, name, department, salary) values (35, 'Tann Dobbison', 'Support', 3788.83);
insert into Employees (id, name, department, salary) values (36, 'Mufi Baldwin', 'Sales', 4690.28);
insert into Employees (id, name, department, salary) values (37, 'Devin Kleinberer', 'Business Development', 3019.53);
insert into Employees (id, name, department, salary) values (38, 'Lee Barns', 'Product Management', 1870.96);
insert into Employees (id, name, department, salary) values (39, 'Margarette Docket', 'Services', 4750.15);
insert into Employees (id, name, department, salary) values (40, 'Natividad Posnette', 'Marketing', 1260.39);
insert into Employees (id, name, department, salary) values (41, 'Eydie Karpov', 'Human Resources', 3802.68);
insert into Employees (id, name, department, salary) values (42, 'Kippy Kerwin', 'Legal', 3195.36);
insert into Employees (id, name, department, salary) values (43, 'Erskine MacArte', 'Training', 1591.56);
insert into Employees (id, name, department, salary) values (44, 'Kalina Lefever', 'Legal', 3117.53);
insert into Employees (id, name, department, salary) values (45, 'Katharyn Wayman', 'Sales', 1186.8);
insert into Employees (id, name, department, salary) values (46, 'Leontyne Macvey', 'Marketing', 4221.04);
insert into Employees (id, name, department, salary) values (47, 'Rollo Tenbrug', 'Research and Development', 1244.0);
insert into Employees (id, name, department, salary) values (48, 'Selma Van Zon', 'Marketing', 2081.98);
insert into Employees (id, name, department, salary) values (49, 'Anthia Ord', 'Legal', 2383.1);
insert into Employees (id, name, department, salary) values (50, 'Loleta Blamphin', 'Engineering', 1409.39);
insert into Employees (id, name, department, salary) values (51, 'Spense Starkie', 'Services', 2262.85);
insert into Employees (id, name, department, salary) values (52, 'Tod Yonge', 'Engineering', 2811.7);
insert into Employees (id, name, department, salary) values (53, 'Jordana Foulks', 'Training', 4595.13);
insert into Employees (id, name, department, salary) values (54, 'Irvine Flye', 'Product Management', 2290.07);
insert into Employees (id, name, department, salary) values (55, 'Maye Crust', 'Accounting', 2399.02);
insert into Employees (id, name, department, salary) values (56, 'Leone Blatherwick', 'Marketing', 4732.04);
insert into Employees (id, name, department, salary) values (57, 'Sly Stead', 'Sales', 3750.96);
insert into Employees (id, name, department, salary) values (58, 'Maurise Boyce', 'Sales', 3557.16);
insert into Employees (id, name, department, salary) values (59, 'Brade Gummory', 'Research and Development', 4908.96);
insert into Employees (id, name, department, salary) values (60, 'Meggi Braun', 'Training', 3784.18);
insert into Employees (id, name, department, salary) values (61, 'Kalindi Ayree', 'Marketing', 2244.33);
insert into Employees (id, name, department, salary) values (62, 'Kimberly Woodward', 'Product Management', 3606.73);
insert into Employees (id, name, department, salary) values (63, 'Adda Chiles', 'Product Management', 3527.52);
insert into Employees (id, name, department, salary) values (64, 'Augustine Coatman', 'Research and Development', 4854.48);
insert into Employees (id, name, department, salary) values (65, 'Ezekiel Siseland', 'Training', 4123.59);
insert into Employees (id, name, department, salary) values (66, 'Kerr Chipchase', 'Marketing', 4428.68);
insert into Employees (id, name, department, salary) values (67, 'Gilles Brendel', 'Services', 3887.79);
insert into Employees (id, name, department, salary) values (68, 'Delcine Avrasin', 'Support', 4666.08);
insert into Employees (id, name, department, salary) values (69, 'Norrie Petti', 'Training', 4522.54);
insert into Employees (id, name, department, salary) values (70, 'Jedediah Toop', 'Support', 3297.39);
insert into Employees (id, name, department, salary) values (71, 'Manfred Boyall', 'Business Development', 1466.59);
insert into Employees (id, name, department, salary) values (72, 'Donnie Manoelli', 'Support', 1892.64);
insert into Employees (id, name, department, salary) values (73, 'Edwin Rentoul', 'Business Development', 4680.88);
insert into Employees (id, name, department, salary) values (74, 'Kirbie Speak', 'Marketing', 2864.42);
insert into Employees (id, name, department, salary) values (75, 'Megen Lusk', 'Human Resources', 4471.93);
insert into Employees (id, name, department, salary) values (76, 'Kerstin Zanetti', 'Training', 4769.21);
insert into Employees (id, name, department, salary) values (77, 'Othelia Fouracre', 'Marketing', 3332.33);
insert into Employees (id, name, department, salary) values (78, 'Ethelda Harkins', 'Human Resources', 3143.35);
insert into Employees (id, name, department, salary) values (79, 'Culley Millsap', 'Training', 3040.02);
insert into Employees (id, name, department, salary) values (80, 'Josephine Klimowicz', 'Support', 3673.09);
insert into Employees (id, name, department, salary) values (81, 'Levin Luttger', 'Accounting', 2785.26);
insert into Employees (id, name, department, salary) values (82, 'Coop Mattosoff', 'Training', 3272.94);
insert into Employees (id, name, department, salary) values (83, 'Vonny Zanelli', 'Training', 1727.39);
insert into Employees (id, name, department, salary) values (84, 'Wanda Ohrt', 'Product Management', 4750.84);
insert into Employees (id, name, department, salary) values (85, 'Marget Linne', 'Marketing', 3156.27);
insert into Employees (id, name, department, salary) values (86, 'Leisha De''Ath', 'Sales', 3975.09);
insert into Employees (id, name, department, salary) values (87, 'Jeremie Hachard', 'Sales', 4911.41);
insert into Employees (id, name, department, salary) values (88, 'Marjorie Barling', 'Accounting', 4608.75);
insert into Employees (id, name, department, salary) values (89, 'Pincus Aldersey', 'Human Resources', 3935.24);
insert into Employees (id, name, department, salary) values (90, 'Gordie Forsdyke', 'Legal', 2506.79);
insert into Employees (id, name, department, salary) values (91, 'Robby Tarn', 'Human Resources', 1365.5);
insert into Employees (id, name, department, salary) values (92, 'Mandy Stacy', 'Research and Development', 3577.07);
insert into Employees (id, name, department, salary) values (93, 'Deirdre Dyson', 'Product Management', 1470.71);
insert into Employees (id, name, department, salary) values (94, 'Fania Rosenblum', 'Research and Development', 3178.39);
insert into Employees (id, name, department, salary) values (95, 'Zaria Scotchbrook', 'Sales', 3999.41);
insert into Employees (id, name, department, salary) values (96, 'Rachael Todarello', 'Legal', 1036.64);
insert into Employees (id, name, department, salary) values (97, 'Joanna McClenaghan', 'Accounting', 2432.25);
insert into Employees (id, name, department, salary) values (98, 'Lonna Dymock', 'Human Resources', 2960.0);
insert into Employees (id, name, department, salary) values (99, 'Marcelle Mandry', 'Training', 1452.02);
insert into Employees (id, name, department, salary) values (100, 'Gerhard Riddeough', 'Services', 3299.62);
